[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "socaity-face2face"
version = "0.0.6"
description="Swap faces from one image to another. Create face embeddings. Integrate into hosted environments."
requires-python = ">=3.8"
authors = [
    { name = "SocAIty" }
]
license = { text = "GPLv3" }
readme = "README.md"
dependencies = [
    'insightface==0.7.3',
    'onnxruntime-gpu==1.15.1',
    'media-toolkit[VideoFile]>=0.0.7',
]

[project.urls]
Repository = "https://github.com/SocAIty/face2face"


[project.optional-dependencies]
full = [
    "fast-task-api[full]>=0.0.4",
]
